Parameters:
  SSHLocation:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
    Description: 'SSH: Please set CIDR to x.x.x.x/32 to allow one specific IP address access, 0.0.0.0/0 to allow all IP addresses access, or another CIDR range.'
    MaxLength: 18
    MinLength: 9
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    AllowedPattern: .+
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Description: Name of an existing EC2 key pair to enable SSH access to the instance
  InstanceType:
    Type: String
    Default: c5n.9xlarge
    Description: EC2 instance type
  VPCID:
    Type: AWS::EC2::VPC::Id
    AllowedPattern: .+
    Description: ID of pre-existing vpc.
  SubetIDCDIA:
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: .+
    Description: ID of pre-existing subnet.
Resources:
  SGsMyCfnSecurityGroupA0E5FF69:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sbx-cdi
      GroupName: sbx-cdi
      Tags:
        - Key: Name
          Value: sbx-cdi
      VpcId:
        Ref: VPCID
  SGsACTL3UDPB94FEE9A:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: udp
      CidrIp: 0.0.0.0/0
      Description: Allow ACT-L3 inbound
      FromPort: 1770
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      ToPort: 1780
  SGsACTL3TCPDE340485:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: Allow ACT-L3 inbound
      FromPort: 1770
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      ToPort: 1780
  SGsHTTP81848A1A:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: Allow HTTP access from the internet
      FromPort: 80
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      ToPort: 80
  SGsHTTPS92ABDDE2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: Allow HTTPS access from the internet
      FromPort: 443
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      ToPort: 443
  SGsSSH44508AD9:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp:
        Ref: SSHLocation
      Description: Allow SSH access from the internet
      FromPort: 22
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      ToPort: 22
  SGsEnableEFAIngressA11F7208:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: "-1"
      Description: Allow all traffic from myself
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
    Metadata:
      aws:cdk:path: NetworkStack/SGs/Enable EFA Ingress
  SGsEnableEFAegressD7BE2DBA:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      IpProtocol: "-1"
      Description: Allow all traffic from myself
      DestinationSecurityGroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
  SGsEnablealloutboundegress37F6CF43:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt:
          - SGsMyCfnSecurityGroupA0E5FF69
          - GroupId
      IpProtocol: "-1"
      CidrIp: 0.0.0.0/0
      Description: Allow all traffic out
  rtablescdiArtableA59AF960:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCID
      Tags:
        - Key: Name
          Value: sbx-cdiA
  rtablescdiAsrtaA81E8116:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Fn::GetAtt:
          - rtablescdiArtableA59AF960
          - RouteTableId
      SubnetId:
        Ref: SubetIDCDIA
  CDIcdirole92665D66:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - ec2.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      Description: Role for sbx CDI instances
      RoleName:
        Fn::Join:
          - ""
          - - sbx-cdi-
            - Ref: AWS::Region
  CDIcdiroleDefaultPolicyE3F2C3C7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: mediaconnect:*
            Effect: Allow
            Resource: '*'
        Version: "2012-10-17"
      PolicyName: CDIcdiroleDefaultPolicyE3F2C3C7
      Roles:
        - Ref: CDIcdirole92665D66
  CDIcdiInstanceProfile73CBEB23:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: CDIcdirole92665D66
      InstanceProfileName:
        Fn::Join:
          - ""
          - - cdiInstanceProfile-
            - Ref: AWS::Region
  CDIlaunchtemplate8761A726:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
              - CDIcdiInstanceProfile73CBEB23
              - Arn
        ImageId:
          Fn::FindInMap:
            - CDIRegionMapEF10A6AE
            - Ref: AWS::Region
            - ami
        InstanceType:
          Ref: InstanceType
        KeyName:
          Ref: KeyName
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            Groups:
              - Fn::GetAtt:
                  - SGsMyCfnSecurityGroupA0E5FF69
                  - GroupId
            InterfaceType: efa
            SubnetId:
              Ref: SubetIDCDIA
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: sbx-cdi
        UserData:
          Fn::Base64: |
            #!/usr/bin/env bash
            /opt/sbx/InstallSbxCDI/sanity_check
            PATH=/opt/amazon/efa/bin:$PATH /opt/sbx/InstallSbxCDI/aws-efa-installer/efa_test.sh
      LaunchTemplateName: sbx-cdi
  CDIInstance18DD8688F:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      LaunchTemplate:
        LaunchTemplateId:
          Ref: CDIlaunchtemplate8761A726
        Version:
          Fn::GetAtt:
            - CDIlaunchtemplate8761A726
            - LatestVersionNumber
      Tags:
        - Key: Name
          Value: sbx-cdi
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WOQW+CQBCFf4t32FZiTK+GNIbEpgRNr82wjDoKs2R3tsYQ/nthaeXgad58M3nvJSpZqeUCbi7W1TWuqVTdXkBfo/TIOVhoUNBGw/27Q52obsBfeTpe975klKBQe0ty31rj2yeQ8cmic0/8/YEzHjIGry0I3uAeTRl/20aGOucGOUQVxgseoKxxrjCzjXNGEwgZfjyPYgee9fmATVvDRDJ2Aqyxjwga1RVmMgwzNzXp0GJW//+5NUeqse9H+AFtS3wa5aeX1k8N0RlvdbBLDVc0tukjNhWqi3v5Wb6ptXpdXBxRbD0LNaiKaf4CO670Do0BAAA=
    Metadata:
      aws:cdk:path: NetworkStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Mappings:
  CDIRegionMapEF10A6AE:
    af-south-1:
      ami: ami-029ea7c67eb175492
    ap-east-1:
      ami: ami-0db45bfafd387f211
    ap-northeast-1:
      ami: ami-095479d0f5fd754b2
    ap-northeast-2:
      ami: ami-03dac10390e25bfed
    ap-northeast-3:
      ami: ami-05cd00e8e31056536
    ap-south-1:
      ami: ami-0addce7703ae20ea5
    ap-southeast-1:
      ami: ami-05ead723d32dac9db
    ap-southeast-2:
      ami: ami-00514ba46a0948a45
    ap-southeast-3:
      ami: ami-0fe35f4d5f343ecf1
    ca-central-1:
      ami: ami-072175f109d9408b1
    eu-central-1:
      ami: ami-003197dae1192087f
    eu-north-1:
      ami: ami-083823e5aa2833121
    eu-south-1:
      ami: ami-00593819934617284
    eu-west-1:
      ami: ami-0980abe0977dbd00d
    eu-west-2:
      ami: ami-0ee916316055089a5
    eu-west-3:
      ami: ami-0f66d5634e8afdca8
    me-south-1:
      ami: ami-003fb8fbf67a0dcc4
    sa-east-1:
      ami: ami-0eb79362cb8f59789
    us-east-1:
      ami: ami-08d996ad41b263466
    us-east-2:
      ami: ami-0d47d5e3f4f198110
    us-west-1:
      ami: ami-0839ab0bb206d9f9b
    us-west-2:
      ami: ami-0d01bfeb56fa54146
Outputs:
  CDIpublicIp2E8E33E7:
    Description: Instance Public Ip
    Value:
      Fn::GetAtt:
        - CDIInstance18DD8688F
        - PublicIp
    Export:
      Name: ec2-public-ip
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
