#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
Parameters:
  #@overlay/match missing_ok=True
  VPCID:
    Type: AWS::EC2::VPC::Id
    AllowedPattern: .+
  #@overlay/match missing_ok=True
  SubetIDCDIA:
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: .+
